### ISSUE TITLE
Renomear Organização e Usuário @opensciense

### ISSUE THREAD

**Issue by alcemirsantos** [Openscience-se-org/opensciense.github.io#1]
Estou pensando em ajustar os repositórios da organização do workshop nas próximas semanas. 

Acredito que seria interessante termos a seguinte estrutura de páginas: 

* [opensciense.github.io](http://opensciense.github.io/): o portal principal
   * [openscienceXX](#): um portal para cada  uma das edições o workshop

Portanto, uma vez que o objetivo principal é simplificar o `url` do site da organização, queria fazer as seguintes sugestões para podermos caminhar nesta direção:

1.  **renomear a organização para** `opensciense` ou `opensiense-org` (para que este repositório se torno e portal geral -- aquele com a referência para edições anteiores -- fique _opensciense_ ou _opensiense-org_ `.github.io`).  **Ou**
2. `renomear este repositório para o nome da organização` (para openscience-se-org) para que se torne automaticamente o portal, se precisar chamar [openscience-se-org.github.io/opensciense.github.io](https://openscience-se-org.github.io/opensciense.github.io/) .

ps: A depender da escolha, o usuário @opensciense já possui esse nickname, teríamos que renomea-lo ele também.

**Comment by christinaflach** [comment]
Organização renomeada segundo solicitado em 1.

**Comment by christinaflach** [comment]
Repositório renomeado segundo solicitado em 2.
Confere @alcemirsantos ?

**Comment by alcemirsantos** [comment]
@christinaflach  o nome do repositório tem que ser exatamente igual ao nome da organização.  Vi que tenho permissão para fazer a troca. Vou fazer, qualquer coisa, podemos desfazer a mudança. 

A _issue_ era mais para garantir que poderia ser mudado.

**Comment by alcemirsantos** [comment]
Organização e repositório renomeados. 

Agora já é possível acessar o [portal](https://opensciense-org.github.io/) com um endereço simplificado:
``https://opensciense-org.github.io/``
Ademais,  cada um dos próximos projetos pode ser acessado em cascata:

- OpenScienSE 2021: [https://opensciense-org.github.io/opensciense2021/](https://opensciense-org.github.io/opensciense2021/)
- OpenScienSE 2022: [https://opensciense-org.github.io/opensciense2022/](https://opensciense-org.github.io/opensciense2022/)

ps: precisamos verificar os links em cada página que a renomeação do portal e da  organização eventualmente tenham quebrado.

**Comment by alcemirsantos** [comment]
Vou encerrar a issue, visto que a alteração não foi questionada.
